SELECT PERSON.FULLNAME, COUNT(DISTINCT w.WRITERROLEID) AS TOTAL_WRITER_ROLES FROM C##DB2025.PERSON
JOIN C##DB2025.WRITER w  ON PERSON.PERSONID = w.PERSONID
GROUP BY PERSON.FULLNAME
ORDER BY TOTAL_WRITER_ROLES DESC, PERSON.FULLNAME ASC 
FETCH FIRST 10 ROWS ONLY 
