WITH CombinedClips AS (
    SELECT PERSONID, CLIPID FROM C##DB2025.DIRECTOR
    UNION
    SELECT PERSONID, CLIPID FROM C##DB2025.WRITER
    UNION
    SELECT PERSONID, CLIPID FROM C##DB2025.ACTOR
)
SELECT PERSONID, COUNT(CLIPID) AS TOTAL_CLIPS
FROM CombinedClips
GROUP BY PERSONID
ORDER BY TOTAL_CLIPS DESC
FETCH FIRST 10 ROWS ONLY;

