SELECT l.LANGUAGE, count(cl.CLIPID) AS CLIP_COUNT FROM C##DB2025.LANGUAGE l
JOIN C##DB2025.CLIPLANGUAGE cl ON l.LANGUAGEID = cl.LANGUAGEID 
GROUP BY l.LANGUAGE
ORDER BY CLIP_COUNT DESC
FETCH FIRST 10 ROWS ONLY 
