SELECT c.CLIPID , COUNT(d.DIRECTORROLEID) AS NUM_CO_DIRECTORS FROM C##DB2025.CLIP c 
JOIN C##DB2025.DIRECTOR d ON d.CLIPID = c.CLIPID
WHERE d.DIRECTORROLEID = 1
GROUP BY c.CLIPID
ORDER BY NUM_CO_DIRECTORS DESC, c.CLIPID ASC
FETCH FIRST 10 ROWS ONLY 
