SELECT c.CLIPID, cr.RELEASECOUNTRYID, cr.RUNNINGTIMEMINUTES * 60 + cr.RUNNINGTIMESECONDS AS TOTAL_RUNNINGTIME 
FROM C##DB2025.CLIP c 
JOIN C##DB2025.CLIPRUNNINGTIME cr  ON cr.CLIPID  = c.CLIPID
ORDER BY TOTAL_RUNNINGTIME DESC
FETCH FIRST 10 ROWS ONLY 
