SELECT c.COUNTRYNAME, ROUND(AVG(cr.RUNNINGTIMEMINUTES * 60 + cr.RUNNINGTIMESECONDS)) AS AVERAGE_RUNNINGTIME_SECONDS 
FROM C##DB2025.COUNTRY c 
JOIN C##DB2025.CLIPRUNNINGTIME cr  ON cr.RELEASECOUNTRYID  = c.COUNTRYID
GROUP BY c.COUNTRYNAME
ORDER BY c.COUNTRYNAME ASC
FETCH FIRST 10 ROWS ONLY 
