SELECT PERSON.PERSONID, COUNT(DISTINCT a.ACTORROLEID) AS DISTINCT_ACTOR_ROLES FROM C##DB2025.PERSON
JOIN C##DB2025.ACTOR a ON PERSON.PERSONID = a.PERSONID
GROUP BY PERSON.PERSONID
ORDER BY DISTINCT_ACTOR_ROLES DESC
FETCH FIRST 10 ROWS ONLY 
