SELECT c.CLIPID, count(cl.LANGUAGEID) AS NUM_LANGUAGES 
FROM C##DB2025.CLIP c 
JOIN C##DB2025.CLIPLANGUAGE cl ON cl.CLIPID  = c.CLIPID
GROUP BY c.CLIPID
ORDER BY NUM_LANGUAGES DESC, c.CLIPID ASC
FETCH FIRST 10 ROWS ONLY 
