SELECT l.LANGUAGE, count(DISTINCT cl.CLIPID) AS CLIP_COUNT 
FROM C##DB2025.LANGUAGE l 
JOIN C##DB2025.CLIPLANGUAGE cl ON cl.LANGUAGEID = l.LANGUAGEID
JOIN C##DB2025.ACTOR a ON cl.CLIPID = a.CLIPID
WHERE a.ACTORROLEID = 1
GROUP BY l.LANGUAGE
ORDER BY CLIP_COUNT DESC
FETCH FIRST 10 ROWS ONLY 
