SELECT PERSON.PERSONID FROM C##DB2025.PERSON
JOIN C##DB2025.PRODUCER p ON PERSON.PERSONID = p.PERSONID
JOIN C##DB2025.DIRECTOR d ON PERSON.PERSONID = d.PERSONID
GROUP BY PERSON.PERSONID
HAVING count(CASE WHEN p.CLIPID = d.CLIPID THEN 1 END) >= 2
ORDER BY PERSON.PERSONID ASC
FETCH FIRST 10 ROWS ONLY 
